"""empty message

Revision ID: 0b90f6b6edfe
Revises: 
Create Date: 2022-03-02 16:27:23.017134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b90f6b6edfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_channel',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=32), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('utime', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('news_comment_liking',
    sa.Column('liking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('liking_id')
    )
    op.create_table('user_basic',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=32), nullable=True),
    sa.Column('profile_photo', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_media', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('introduction', sa.String(length=128), nullable=True),
    sa.Column('certificate', sa.String(length=64), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('news_basic',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cover', sa.String(length=32), nullable=True),
    sa.Column('is_advertising', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('good_count', sa.Integer(), nullable=True),
    sa.Column('allow_comment', sa.Boolean(), nullable=True),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.Column('utime', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['news_channel.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('ratation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('foller_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['foller_id'], ['user_basic.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'foller_id')
    )
    op.create_table('search_history',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('user_channel',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['news_channel.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'cid')
    )
    op.create_table('collection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_basic.nid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    op.create_table('news_comment',
    sa.Column('cmid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_basic.nid'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['news_comment.cmid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('cmid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_comment')
    op.drop_table('collection')
    op.drop_table('user_channel')
    op.drop_table('search_history')
    op.drop_table('ratation')
    op.drop_table('news_basic')
    op.drop_table('user_basic')
    op.drop_table('news_comment_liking')
    op.drop_table('news_channel')
    op.drop_table('book')
    # ### end Alembic commands ###
