"""empty message

Revision ID: 0ec2c60ff88c
Revises: 95db2bc780c1
Create Date: 2022-03-09 11:42:02.790821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ec2c60ff88c'
down_revision = '95db2bc780c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_collection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_basic.nid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    op.drop_table('collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('(`is_delete` in (0,1))', name='collection_chk_1'),
    sa.ForeignKeyConstraint(['news_id'], ['news_basic.nid'], name='collection_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.uid'], name='collection_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'news_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('news_collection')
    # ### end Alembic commands ###
