"""empty message

Revision ID: 1886e7368716
Revises: 2569fbb38206
Create Date: 2022-04-02 17:02:41.028981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1886e7368716'
down_revision = '2569fbb38206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_chapters',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('serial_num', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['tb_course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_sections',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('serial_num', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('learn_time', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=256), nullable=True),
    sa.Column('seq_num', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapters'], ['tb_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course_tag', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('course_tag', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('course_tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tb_course', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tb_course', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('tb_course', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tb_course_tag', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tb_course_tag', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('tb_course_tag', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_course_tag', 'user_id')
    op.drop_column('tb_course_tag', 'update_time')
    op.drop_column('tb_course_tag', 'create_time')
    op.drop_column('tb_course', 'user_id')
    op.drop_column('tb_course', 'update_time')
    op.drop_column('tb_course', 'create_time')
    op.drop_column('course_tag', 'user_id')
    op.drop_column('course_tag', 'update_time')
    op.drop_column('course_tag', 'create_time')
    op.drop_table('tb_sections')
    op.drop_table('tb_chapters')
    # ### end Alembic commands ###
