"""empty message

Revision ID: 2569fbb38206
Revises: 
Create Date: 2022-03-30 10:41:40.985294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2569fbb38206'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_course_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('img_path', sa.String(length=256), nullable=True),
    sa.Column('course_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('learner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_type'], ['tb_course_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=32), nullable=True),
    sa.Column('profile_photo', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('vip', sa.Integer(), nullable=True),
    sa.Column('vip_expiration', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vip'], ['vip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_tag',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['tb_course.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tb_course_tag.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'tag_id')
    )
    op.create_table('oauth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.String(length=512), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('oauth_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_basic', 'superusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_basic', sa.Column('superusers', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('oauth_user')
    op.drop_table('course_tag')
    op.drop_table('user')
    op.drop_table('tb_course')
    op.drop_table('vip')
    op.drop_table('tb_course_type')
    op.drop_table('tb_course_tag')
    op.drop_table('books')
    # ### end Alembic commands ###
