"""empty message

Revision ID: 4ed0a035317f
Revises: 6e483ab7ee16
Create Date: 2022-03-09 09:18:09.721329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed0a035317f'
down_revision = '6e483ab7ee16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channel',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['news_channel.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user_basic.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'cid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_channel')
    # ### end Alembic commands ###
