"""empty message

Revision ID: efed5a6559e4
Revises: 0b90f6b6edfe
Create Date: 2022-03-03 16:53:01.910305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efed5a6559e4'
down_revision = '0b90f6b6edfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_basic', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_basic', type_='unique')
    # ### end Alembic commands ###
